buddybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_wheel_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: bar_to_front_wheel_L
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_wheel_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: bar_to_front_wheel_R
    pid: {p: 100.0, i: 0.01, d: 10.0}
