local_costmap:
  global_frame: /diff_controller/odom
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 300.0
  height: 300.0
  resolution: 0.05
